# MCBDaily Plugin Configuration
# ===========================

# Cooldown time in hours (default: 24 hours)
cooldown-hours: 24

# GUI Configuration
# Supports both legacy color codes (&a, &c, etc.) and MiniMessage format
# MiniMessage examples: <gradient:#ff0000:#00ff00>text</gradient>, <rainbow>text</rainbow>
gui:
  # Title of the GUI
  title: "<gradient:#ffaa00:#ff6600>Daily Rewards</gradient>"
  
  # Auto-refresh interval in seconds (0 to disable)
  auto-refresh-seconds: 5
  
  # Claimable item configuration (lime concrete)
  claimable:
    display-name: "<gradient:#00ff00:#55ff55><bold>Daily Reward</bold></gradient>"
    lore:
      - "&7Click to claim your daily reward!"
      - ""
      - "<yellow>Rewards:</yellow>"
      - "%rewards%"
  
  # Cooldown item configuration (red concrete)  
  cooldown:
    display-name: "<gradient:#ff0000:#ff5555><bold>Daily Reward</bold></gradient>"
    lore:
      - "&7You can claim again in:"
      - "<red><bold>%countdown%</bold></red>"
      - ""
      - "<yellow>Rewards:</yellow>"
      - "%rewards%"

# List of commands to execute when a player claims their daily reward
# Use %player% as a placeholder for the player's name
rewards:
  - "give %player% diamond 1"
  - "give %player% emerald 5"
  - "give %player% gold_ingot 10"
  - "eco give %player% 1000"
  - "msg %player% &aYou have received your daily reward!"

# Debug mode (logs additional information)
debug: false 