# MCBDaily Plugin Configuration
# ===========================

# Cooldown time in hours (default: 24 hours)
cooldown-hours: 24

# GUI Configuration
# Supports both legacy color codes (&a, &c, etc.) and MiniMessage format
# MiniMessage examples: <gradient:#ff0000:#00ff00>text</gradient>, <rainbow>text</rainbow>
gui:
  # Title of the GUI
  title: "<b><gradient:#FF899F:#7AEC6A>DAILY </gradient><gradient:#7AEC6A:#6CC1FF>REWARD</gradient></b>"
  
  # Auto-refresh interval in seconds (0 to disable)
  auto-refresh-seconds: 1
  
  # Claimable item configuration (lime concrete)
  claimable:
    display-name: "<b><#7AEC6A>Daily Reward</#7AEC6A></b>"
    lore:
      - ""
      - "&7Click to claim your daily reward!"
      - ""
  
  # Cooldown item configuration (red concrete)  
  cooldown:
    display-name: "<b><#da2552>Daily Reward</#da2552></b>"
    lore:
      - ""
      - "&7You can claim again in:"
      - "<#da2552><bold>%countdown%</bold></#da2552>"
      - ""

# Claim Messages Configuration
messages:
  # Message sent to the player when they claim their reward
  # Supports both legacy (&) and MiniMessage format
  claim-success: "<gradient:#00ff00:#55ff55><bold>Daily reward claimed successfully!</bold></gradient>"
  
  # Broadcast settings
  broadcast:
    # Enable/disable server-wide broadcast when someone claims
    enabled: true
    
    # Send broadcast to console as well
    console-log: true
    
    # Exclude the claiming player from receiving the broadcast
    exclude-claimer: false
    
    # Broadcast message (supports %player% placeholder)
    # Use both legacy and MiniMessage formatting
    message: "<b><#fec76f>DAILY REWARD</b> <dark_gray>» <b><#fec76f>%player%</b> <gray>has claimed their daily reward. Claim yours with <b><#fec76f>/daily"
    
    # Alternative broadcast messages (random selection)
    # Leave empty to use only the main message
    random-messages: []

# List of commands to execute when a player claims their daily reward
# Use %player% as a placeholder for the player's name
rewards:
  - "give %player% diamond 1"
  - "give %player% emerald 5"
  - "give %player% gold_ingot 10"
  - "eco give %player% 1000"

# Debug mode (logs additional information)
debug: false 