# MCBDaily Plugin Configuration
# ===========================

# Cooldown time in hours (default: 24 hours)
cooldown-hours: 24

# GUI Configuration
gui:
  # Title of the GUI
  title: "&6Daily Rewards"
  
  # Auto-refresh interval in seconds (0 to disable)
  auto-refresh-seconds: 5
  
  # Claimable item configuration (lime concrete)
  claimable:
    display-name: "&a&lDaily Reward"
    lore:
      - "&7Click to claim your daily reward!"
      - ""
      - "&eRewards:"
      - "%rewards%"
  
  # Cooldown item configuration (red concrete)  
  cooldown:
    display-name: "&c&lDaily Reward"
    lore:
      - "&7You can claim again in:"
      - "&c%countdown%"
      - ""
      - "&eRewards:"
      - "%rewards%"

# List of commands to execute when a player claims their daily reward
# Use %player% as a placeholder for the player's name
rewards:
  - "give %player% diamond 1"
  - "give %player% emerald 5"
  - "give %player% gold_ingot 10"
  - "eco give %player% 1000"
  - "msg %player% &aYou have received your daily reward!"

# Debug mode (logs additional information)
debug: false 